name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ruby-multi-version:latest

  push:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Tag the Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}"/ruby-multi-version
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          docker tag ruby-multi-version:latest $IMAGE_NAME:latest
          docker tag ruby-multi-version:latest $IMAGE_NAME:$TIMESTAMP

      - name: Push the Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}"/ruby-multi-version:latest
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TIMESTAMP